common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    gps_topic: "/gps/data"       
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line:  6
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    gps_cov: 0.01                  
    fov_degree:    180
    det_range:     260.0
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ] # Lidar center w/r/t IMU
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: true       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame
    gps_publish_en: true         

# GPS Settings
    useImuHeadingInitialization: false           # if using GPS data, set to "true"
    useGpsElevation: false                      # if GPS elevation is bad, set to "false"
    gpsCovThreshold: 2.0                        # m^2, threshold for using GPS data
    poseCovThreshold: 0 #25.0                      # m^2, threshold for using GPS data  pose covariance threshold from isam2