common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line:  6
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     260.0
    extrinsic_T: [ -0.011, -0.02329, -0.04412 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

    #extrinsic_R: [  0.9238795,  0.0000000,  0.3826834,
    #                0.0000000,  1.0000000,  0.0000000,
    #                -0.3826834,  0.0000000,  0.9238795 ]

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: true       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame