/**:
    ros__parameters:
        reconstructKdTree: true
        updateState: true
        updateFrequency: 30
        max_iteration: 3
        map_file_path: "./test.pcd"
        filter_size_corner: 0.5
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        point_filter_num: 4
        feature_extract_enable: false
        debug_mode_enable: false
        pcd_save_enable: false
        visualize_map: true

        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/mavros/imu/data"
            time_sync_en: true            # ONLY turn on when external time synchronization is really not possible

        preprocess:
            lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 16
            blind: 1.0

        mapping:
            det_range:     100.0
            fov_degree:    180.0
            gyr_cov: 0.1
            acc_cov: 0.1
            b_gyr_cov: 0.0001
            b_acc_cov: 0.0001
            extrinsic_T: [ 0., 0., 0.28]
            extrinsic_R: [ 1., 0., 0., 
                        0., 1., 0., 
                        0., 0., 1.]

        publish:
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
